docker_base_compose_version: "1.24.1"
docker_base_compose_bin: /usr/local/bin/docker-compose
docker_base_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_base_compose_version }}/docker-compose-"

# Docker configuration
docker_base_daemon_path: "/etc/docker/daemon.json"
docker_base_insecure_registries: []
docker_base_mirrors: []
docker_base_username: ""
docker_base_password: ""
