# vim: set ft=Ansible ts=2


- name: Include OS tasks
  include_tasks:
    file: "{{ ansible_system | lower }}_{{ ansible_distribution | lower }}.yml"
  tags: [always]


- name: Install Python dependencies
  ansible.builtin.pip:
    name: "{{ jpclipffel_container_docker_pip_packages }}"
    state: present
  tags: [never, setup, teardown, remove]
