# vim: set ft=Ansible ts=2


- name: Install Containerd
  ansible.builtin.package:
    name: containerd
    state: present
  tags: [never, setup]


- name: Enable Containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
  tags: [never, setup]


- name: Disable Containerd service
  ansible.builtin.systemd:
    name: containerd
    state: stopped
    enabled: no
  tags: [never, teardown, remove]


- name: Uninstall Containerd
  ansible.builtin.package:
    name: containerd
    state: absent
  tags: [never, remove]
